In [13]:
from Maze.Generator import PerlinMazeGenerator, DFSMazeGenerator
from Maze.Maze import Maze
import numpy as np

In [14]:
perlin_gen = PerlinMazeGenerator(size=16)

perlin_grid = perlin_gen.initialize_genome()

print("Perlin Grid Shape:", perlin_grid.shape)
print(perlin_grid)

Perlin Grid Shape: (16, 16)
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1]
 [1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1]
 [1 0 2 0 2 2 0 0 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1]
 [1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
 [1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1]
 [1 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1]
 [1 0 0 0 1 1 0 0 0 1 1 1 0 0 0 1]
 [1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1]
 [1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1]
 [1 1 1 0 2 0 0 0 0 0 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1 1 1 1 1 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [15]:
dfs_gen = DFSMazeGenerator(size=16)

dfs_grid = dfs_gen.initialize_genome()

print("DFS Grid Shape:", dfs_grid.shape)
print(dfs_grid)

DFS Grid Shape: (16, 16)
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [1 0 1 0 1 1 1 1 1 0 1 0 1 0 1 1]
 [1 0 0 0 1 0 0 0 1 0 1 0 1 0 1 1]
 [1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1]
 [1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1]
 [1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1]
 [1 0 1 2 0 0 1 0 1 0 0 0 1 0 1 1]
 [1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 1]
 [1 0 1 0 0 0 1 0 0 0 0 2 1 2 1 1]
 [1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1]
 [1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 1]
 [1 0 1 0 1 0 1 2 1 1 1 1 1 0 1 1]
 [1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [16]:
# Junction Test:
gen = PerlinMazeGenerator(size=16)
grid = gen.initialize_genome()
maze = Maze(grid)
print(maze.to_ascii())
print(maze._openness_score())

gen2 = DFSMazeGenerator(size=16)
grid2 = gen2.initialize_genome()
maze2 = Maze(grid2)
print(maze2.to_ascii())
print(maze2._openness_score())

████████████████
█G  □       ████
██          ████
██         █████
█          █████
█     ███     ██
█      █    ████
██         █████
███       ████ █
████□    S████ █
████       ██  █
█████      ██  █
█ ███    □ ███ █
█  ██     ████ █
█         ███  █
████████████████
86.67657470703125
████████████████
█      □□ █   ██
█S█ █████ ███ ██
█ █ █   █   █ ██
███ █ █ ███ █ ██
█   █ █   █   ██
█████ ███□███ ██
█     █     █ ██
█ █████ ███ █ ██
█ █   █ █  G█ ██
█ █ █ █ ███ █□██
█ █ █ █   █ █ ██
█ ███ ███ ███ ██
█       █     ██
████████████████
████████████████
5.796818621134021


In [17]:
gen = PerlinMazeGenerator(size=16)
grid = gen.initialize_genome()
maze = Maze(grid)
score = maze.evaluate_structure()

print("Score:", score)
print("Start:", maze.Start, "Goal:", maze.Goal)
print(maze.to_ascii())

Score: (164.32195526541096, 46.0)
Start: (6, 5) Goal: (14, 3)
████████████████
█  ███         █
█ ████         █
███████        █
██████         █
█████        □ █
████ S         █
███    █       █
██     █       █
█    □██       █
█    ██   █    █
█ □ ███   ██   █
█   ███   ██   █
█   ██ □       █
█  G██    █    █
████████████████


In [18]:
gen = DFSMazeGenerator(size=16)
grid = gen.initialize_genome()
maze = Maze(grid)
score = maze.evaluate_structure()

print("Score:", score)
print("Start:", maze.Start, "Goal:", maze.Goal)
print(maze.to_ascii())

Score: (249.21481556056702, 114.0)
Start: (5, 13) Goal: (11, 11)
████████████████
█             ██
█████████ ██████
█    □  █ █   ██
█ █████ █ █ █ ██
█ █   █ █□█ █S██
█ █ █ █ █ ███ ██
█   █ █     █ ██
█ ███ █ █████ ██
█ █   █ █     ██
█ █ █████ ██████
█ █     █ █G□ ██
█ █████ █ ███ ██
█ □   █       ██
████████████████
████████████████
