In [1]:
from Maze.Generator import PerlinMazeGenerator, DFSMazeGenerator
from Maze.Maze import Maze
import numpy as np

In [2]:
perlin_gen = PerlinMazeGenerator(size=16)

perlin_grid = perlin_gen.initialize_genome()

print("Perlin Grid Shape:", perlin_grid.shape)
print(perlin_grid)

Perlin Grid Shape: (16, 16)
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 0 1 1 1 1 0 0 1]
 [1 1 1 0 2 0 0 0 0 1 1 1 1 0 0 1]
 [1 1 1 0 0 2 0 0 0 1 1 1 1 0 0 1]
 [1 1 1 1 0 0 1 1 0 1 1 1 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1]
 [1 1 1 0 0 0 0 1 0 0 0 0 1 0 0 1]
 [1 0 0 0 0 0 0 0 0 2 2 0 1 1 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 2 0 1 1 1 1 1]
 [1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [3]:
dfs_gen = DFSMazeGenerator(size=16)

dfs_grid = dfs_gen.initialize_genome()

print("DFS Grid Shape:", dfs_grid.shape)
print(dfs_grid)

DFS Grid Shape: (16, 16)
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
 [1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1]
 [1 0 2 0 1 2 0 0 0 0 1 0 0 0 1 1]
 [1 0 1 0 1 1 1 2 1 0 1 0 1 0 1 1]
 [1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1]
 [1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1]
 [1 0 1 0 0 0 1 0 0 2 0 0 1 0 1 1]
 [1 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1]
 [1 0 1 0 1 0 0 0 0 0 0 0 1 0 1 1]
 [1 0 1 0 1 0 1 1 1 1 1 0 1 0 1 1]
 [1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 1]
 [1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1]
 [1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [4]:
# Junction Test:
gen = PerlinMazeGenerator(size=16)
grid = gen.initialize_genome()
maze = Maze(grid)
print(maze.to_ascii())
print(maze._openness_score())

gen2 = DFSMazeGenerator(size=16)
grid2 = gen2.initialize_genome()
maze2 = Maze(grid2)
print(maze2.to_ascii())
print(maze2._openness_score())

████████████████
██      █      █
██  G  ████   ██
██     █████████
██     █████████
██      ████████
█□       ███████
█         ██████
█        ███████
█       ████████
█   ██████████ █
█   ████████   █
█   ███████    █
███ ███████    █
██████████  █S █
████████████████
65.09315159574469
████████████████
█             ██
█ ███████████ ██
█   █       █ ██
█□█ █□█████G████
█ █       █   ██
█ ███████████ ██
█ █  S    █   ██
███ █████ █ █ ██
█   █ █    □█ ██
█ ███ █ ████████
█   █   █   █  █
█ █ █████ █ █ ██
█ █     □ █   ██
████████████████
████████████████
5.798836096938776


In [5]:
gen = PerlinMazeGenerator(size=16)
grid = gen.initialize_genome()
maze = Maze(grid)
score = maze.evaluate_structure()

print("Score:", score)
print("Start:", maze.start, "Goal:", maze.goal)
print(maze.to_ascii())

Score: (-500.0, 0)
Start: (10, 14) Goal: (6, 10)
████████████████
█        □ ███ █
█              █
█              █
█ ███          █
█ ███        □██
█         G  ███
█  □        ████
█    █      ████
█   ██    █ █  █
█   ████ ████ S█
█   █████  ██  █
█   ████   █   █
██  □      ██  █
█         ██████
████████████████


In [6]:
gen = DFSMazeGenerator(size=16)
grid = gen.initialize_genome()
maze = Maze(grid)
score = maze.evaluate_structure()

print("Score:", score)
print("Start:", maze.start, "Goal:", maze.goal)
print(maze.to_ascii())

Score: (154.8138392857143, 67.0)
Start: (11, 7) Goal: (6, 1)
████████████████
█□      █     ██
█ ███████ ███ ██
█     █□  █ █ ██
█ ███ █ ███ █ ██
█ █ █       █ ██
█G█ █████████□██
█ █     █     ██
█ █████ █ ███ ██
█     □ █ █   ██
███████ █ ██████
█      S█     ██
█ ███████████ ██
█     █       ██
███████ ████████
████████████████


In [7]:
from MazeSolver.Solver import AStarSolver
from Archive import MapElitesArchive, Individual
from Controller import ExperimentController

In [8]:
# 1. 生成一张迷宫
gen = PerlinMazeGenerator(size=16)
grid = gen.initialize_genome()
maze = Maze(grid)

print("Start:", maze.start, "Goal:", maze.goal)

# 2. baseline 路径长度（用于对比）
base_fitness, base_steps = maze.evaluate_structure()
print("Baseline steps:", base_steps, "Baseline fitness:", base_fitness)

# 3. 用未进化的 A* Solver 跑
theta0 = np.array([-1.0, -0.5, 0.2, 0.0])
solver = AStarSolver(theta=theta0)

success, steps = solver.solve(maze)
print("Solver success:", success, "Solver steps:", steps)
print("Ratio solver / baseline:", steps / (base_steps + 1e-6))

Start: (1, 11) Goal: (10, 12)
Baseline steps: 40.0 Baseline fitness: 159.9686206210191
Solver success: True Solver steps: 40
Ratio solver / baseline: 0.9999999750000007


In [13]:
gen = PerlinMazeGenerator(size=16)
archive = MapElitesArchive(bins_f1=10, bins_f2=10)
ctrl = ExperimentController(generator=gen, archive=archive)

ctrl.initialize_archive(n=50)

envs = ctrl.sample_envs_for_solver(k=10)
print("Sampled envs:", len(envs))

total = 0
solver = AStarSolver(theta=theta0)

for i, indiv in enumerate(envs):
    maze = Maze(indiv.genome)
    base_fit, base_steps = maze.evaluate_structure()
    success, steps = solver.solve(maze)

    if not success:
        steps_used = 1000
    else:
        steps_used = steps

    print(f"Env {i}: baseline {base_steps}, solver {steps_used}, success={success}")
    total += steps_used

avg_steps = total / max(len(envs), 1)
print("Average solver steps on sampled envs:", avg_steps)

Sampled envs: 9
Env 0: baseline 52.0, solver 52, success=True
Env 1: baseline 37.0, solver 37, success=True
Env 2: baseline 39.0, solver 39, success=True
Env 3: baseline 40.0, solver 40, success=True
Env 4: baseline 28.0, solver 28, success=True
Env 5: baseline 24.0, solver 24, success=True
Env 6: baseline 15.0, solver 15, success=True
Env 7: baseline 18.0, solver 18, success=True
Env 8: baseline 0, solver 1000, success=False
Average solver steps on sampled envs: 139.22222222222223
